---
- name: Start ProwlArr
  when: prowlarr_enabled is true
  block:
    - name: Create ProwlArr Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ prowlarr_config_directory }}"

    - name: Create ProwlArr Docker Container
      community.docker.docker_container:
        name: "{{ prowlarr_container_name }}"
        image: "{{ prowlarr_image_name }}:{{ prowlarr_image_version }}"
        volumes:
          - "{{ prowlarr_config_directory }}:/config"
          - "{{ alexandria_directory }}:/data"
        env:
          TZ: "{{ core_timezone }}"
          PUID: "{{ prowlarr_puid }}"
          PGID: "{{ prowlarr_pgid }}"
        networks:
          - name: "proxy"
        pull: true
        restart_policy: unless-stopped
        labels:
          traefik.enable: "true"
          traefik.http.routers.prowlarr.rule: "Host(`{{ prowlarr_domain }}.{{ lyoko_domain }}`)"
          traefik.http.routers.prowlarr.tls.certresolver: "cloudflare"
          traefik.http.routers.prowlarr.tls.domains[0].main: "{{ lyoko_domain }}"
          traefik.http.routers.prowlarr.tls.domains[0].sans: "*.{{ lyoko_domain }}"
          traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
          traefik.docker.network: "proxy"
