---
# Hostname of the Server
core_hostname: pve-lyoko

# Extra packages to install
core_extra_packages:
  - smartmontools
  - htop
  - zsh
  - gnupg
  - ca-certificates
  - apt-transport-https
  - python3-docker

# Timezone
core_timezone: Europe/Paris
