#cloud-config
hostname: pve-lyoko
manage_etc_hosts: true

users:
  - name: setih
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDCwh6zeUz3fl4FngyugikUQXut4ZWyuymz6pyY9qk94

packages:
  - qemu-guest-agent
  - curl
  - git
  - vim

package_update: true
package_upgrade: true

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent