---
- name: Start QUI
  when: qui_enabled is true
  block:
    - name: Create QUI Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ qui_config_directory }}"

    - name: Create QUI Docker Container
      community.docker.docker_container:
        name: "{{ qui_container_name }}"
        image: "{{ qui_image_name }}:{{ qui_image_version }}"
        volumes:
          - "{{ qui_config_directory }}:/config"
          - "{{ alexandria_directory }}/torrents:/data/torrents"
        env:
          TZ: "{{ core_timezone }}"
          PUID: "{{ qui_puid }}"
          PGID: "{{ qui_pgid }}"
        networks:
          - name: "proxy"
        pull: true
        restart_policy: unless-stopped
        labels:
          traefik.enable: "true"
          traefik.http.routers.qui.rule: "Host(`{{ qui_domain }}.{{ lyoko_domain }}`)"
          traefik.http.routers.qui.entrypoints: "websecure"
          traefik.http.routers.qui.tls.certresolver: "cloudflare"
          traefik.http.services.qui.loadbalancer.server.port: "7476"
          traefik.docker.network: "proxy"
