gluetun_enabled: true

gluetun_config_directory: "{{ apps_directory }}/gluetun"

gluetun_container_name: gluetun
gluetun_image_name: "qmcgaw/gluetun"
gluetun_image_version: latest

wireguard_private_key: ""
wireguard_preshared_key: ""
wireguard_addresses: ""
wireguard_forwarded_port: ""
wireguard_countries: ""